### ISSUE TITLE
DateTime -> DayOfWeek

### ISSUE THREAD

**Issue by dsyme** [fsdn-projects/FSDN#11]
Great work on this site!

I expected this `DateTime -> DayOfWeek` to return the DayOfWeek property.  Are properties ever returned?

**Comment by pocketberserker** [comment]
Please use `receiver => propertyType` query (e.g. `DateTime => DayOfWeek`).

more information: https://github.com/fsdn-projects/FSDN#search-members

**Comment by dsyme** [comment]
Oh I see.  I think it would be better to just unify these - keep the search syntax very, very simple.

**Comment by dsyme** [comment]
I think it's confusing since `string -> int` returns `System.Int32.Parse`.   So I immediately thought `oh good, it searches for members too`.  I understand that's a static method, which matches the given signature.  But as a naive user I was then surprised that properties were not returned.

I do think just always searching for instance members too is the right default

**Comment by yukitos** [comment]
+1 to search members too by `->` by default :+1:

**Comment by pocketberserker** [comment]
Thank you for the suggestion, @dsyme.
We will implement the function here: https://github.com/hafuu/FSharpApiSearch/issues/80
After it's implemented, we will update FSDN web UI to enable the functionality.

**Comment by pocketberserker** [comment]
We applied FSharpApiSearch 0.4.0-beta and deployed few days ago https://twitter.com/htid46/status/747333803216015360 .
