### ISSUE TITLE
Query from URL parameter

### ISSUE THREAD

**Issue by tobia** [fsdn-projects/FSDN#33]
I couldn't find a way to issue a query using a URL parameter (eg. `?q=...`)

This would be useful to add FSDN search to IDEs and browser shortcuts, for example by typing "f ..." in Chrome's address bar.

**Comment by hafuu** [comment]
Please use `query=` parameter.
https://fsdn.azurewebsites.net/?query=string

**Comment by tobia** [comment]
Thank you.
