### ISSUE TITLE
Wrong caret position is reported

### ISSUE THREAD

**Issue by bleis-tift** [fsdn-projects/FSDN#4]
![fireshot capture 6 - fsdn - http___fsdn-stage azurewebsites net_](https://cloud.githubusercontent.com/assets/169348/13312635/97d66e16-dbdb-11e5-85d3-e1b1381aeb26.png)

**Comment by pocketberserker** [comment]
Fix d8b1d34

<img width="431" alt="fix_error_message_layout" src="https://cloud.githubusercontent.com/assets/911952/13338766/ecec7ce8-dc66-11e5-9d48-0afd60a484c6.png">
